### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by Yangzhen0000** [davidsbatista/TAC-Entity-Linking#1]
(About TAC-Entity-Linking) Could you tell me how to use this code?

I am a student doing this research in Shanghai Jiaotong University, China. 
I have tried hard but cannot get the TAC KBP dataset. Besides, I want to find some related work to compare.

**Comment by davidsbatista** [comment]
This is very old code, which needs some corrections to work properly. The TAC datasets you can try to get them from the page of the TAC, but I think you need to have been registered to the challenge at some time. Alternatively you can try to get the datasets from LDC.
